<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
        <img class="product-image-photo lazyload" loading="lazy"
            <?= $block->escapeHtmlAttr($block->getCustomAttributes()) ?>
             data-src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
             width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
             height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
             alt="<?= $block->escapeHtmlAttr($block->stripTags($block->getLabel(), null, true)) ?>"/>
    </span>

    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "ImageObject",
            "image": "<?= $block->escapeUrl($block->getImageUrl()) ?>",
            "name": "<?= $block->escapeJs($block->stripTags($block->getLabel(), null, true)) ?>",
            "description": "<?= $block->escapeJs($block->stripTags($block->getLabel(), null, true)) ?>"
        }
    </script>
</span>
